[package]
name = "yuy-lib"
version = "0.2.0"  # Updated version
edition = "2021"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
syntect = "5.2"
markdown = "1.0"
anyhow = "1.0"
rand = "0.8"

[lib]
crate-type = ["cdylib"]
